#! /bin/bash

# erplag -a file.erp 			--> Generates file.asm
# erplag file.asm				--> Generates file executable 
# erplag -o testExec file.erp   --> Generates executable with the name (Creates temp files)
# erplag file.erp 				--> Generates file executable directly (Creates temp files)

CYAN='\033[1;36m'
RED='\033[1;31m'
BOLD='\033[1m'
RESET='\033[0m'

errHead () {
	printf "${CYAN}ERPLAG : ${RED}FATAL ERROR ${RESET}${BOLD}--> ${RESET}"
}

erpHelp () {
	printf "The compiler can be used with the following options - \n"
	printf "1. ${BOLD}erplag -a mytest.erp ${RESET}generates an x86 asm file with the ${BOLD}mytest.asm${RESET}\n"
	printf "2. ${BOLD}erplag mytest.asm ${RESET}generates an executable file named ${BOLD}mytest ${RESET}from the .asm file\n"
	printf "3. ${BOLD}erplag -o myexec mytest.erp ${RESET}generates an executable file named ${BOLD}myexec${RESET} from the source file\n"
	printf "4. ${BOLD}erplag mytest.erp ${RESET}directly generates an executable file named ${BOLD}mytest ${RESET}from the source file\n"
}

source ~/.bashrc
optflag=0
while getopts ":a:o:h" opt; do
	optflag=1
	case ${opt} in
		h)	erpHelp
			;;
		a)	.compiler $OPTARG
			;;
		o)	target=$OPTARG 
			srcname=$3 

			if test "$srcname" = ""
			then
				errHead
				echo "No source file"
				exit 1
			fi

			asmname=${srcname}.asm
			.compiler $srcname $asmname 
			status=$? 
			if [ $status -eq 0 ]
			then
				objname=${srcname}.o 
				nasm -felf64 $asmname -o $objname 
				gcc -no-pie $objname -o $target 
			fi
			rm -f $asmname
			rm -f $objname
			;;
		\?) errHead
			echo "Invalid option. Use -a to generate x86 assembly or use -o along with output name to generate executable"
			;;
		:)  errHead
			echo "Please provide output file name" 
	esac
done
shift $((OPTIND-1))

if [ $optflag -eq 0 ]
then
	srcname=$1 ;
	if [[ $srcname =~ \.asm$ ]] 
	then
		# Need to check if file exists or not in bash
		if [ -f $srcname ] 
		then
			fname=${srcname:0:${#srcname}-4} 
			objname=${srcname}.o
			nasm -felf64 $srcname -o $objname
			gcc -no-pie $objname -o $fname 
			rm -f $objname
		else
			errHead 
			echo "ASM file $srcname does not exist" 
		fi
	elif [[ $srcname =~ \.erp$ ]] 
	then
		fname=${srcname:0:${#srcname}-4} 
		asmname=${srcname}.asm
		objname=${srcname}.o
		.compiler $srcname $asmname
		status=$? 
		if [ $status -eq 0 ]
		then
			nasm -felf64 $asmname
			gcc -no-pie $objname -o $fname
		fi
		rm -f $asmname
		rm -f $objname
	elif test "$srcname" = ""
	then
		errHead 
		echo "No source file"
	else
		errHead
		echo "Unsupported file format. Use .erp for source files and .asm for x86 assembly files" ;
	fi
fi