#! /bin/bash

BOLD='\033[1m'
RED='\033[1;31m'
RESET='\033[0m'

installErr () {
	printf "\n${BOLD}${RED}ERPLAG installation failed. \nPlease export repository directory to PATH variable.${RESET}\n"
	printf "Press any key to continue..."
	read
}

if [[ "$OSTYPE" == "linux-gnu"* ]]
then
	sudo apt-get update
	sudo apt-get install build-essential
	sudo apt-get install nasm
	make
elif [[ "$OSTYPE" == "darwin"* ]]
then
	var=$(which brew) 
	if test "$var" == ""
	then
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
	fi

	brew update
	brew install gcc
	brew install nasm
else
    printf "${BOLD}${RED}ERPLAG has not been designed for this OS. Please use a linux distribution or MacOS${RESET}\n"
    printf "Press any key to continue..."
	read
    exit
fi


sudo cp erplag /usr/local/bin
stat=$?
if [ $stat -ne 0 ]
then
	installErr 
	exit
fi
sudo cp .compiler /usr/local/bin
stat=$?
if [ $stat -ne 0 ]
then
	installErr 
	exit
fi

make clean

printf "\n${BOLD}ERPLAG compiler has been successfully installed!${RESET}\n"
printf "Use ${BOLD}erplag -h ${RESET}to read the guidelines for using the compiler\n"
printf "Press any key to continue..."
read
