#! /bin/bash

BOLD='\033[1m'
GREEN='\033[1;32m'
RED='\033[1;31m'
RESET='\033[0m'

ccErr () {
	printf "\n${BOLD}${RED}ERPLAG compiler re-build failed.${RESET}\n"
	printf "Press any key to continue...\n"
}

sudo make

sudo cp erplag /usr/local/bin
stat=$?
if [ $stat -ne 0 ]
then
	ccErr
	exit
fi
sudo cp .compiler /usr/local/bin
stat=$?
if [ $stat -ne 0 ]
then
	ccErr
	exit
fi

make clean

printf "\n${BOLD}${GREEN}ERPLAG compiler re-build OK!${RESET}\n"
printf "Press any key to continue..."
read