#! /bin/bash

BOLD='\033[1m'
CYAN='\033[1;36m'
BLUE='\033[1;34m'
MAGENTA='\033[1;35m'
GREEN='\033[1;32m'
RED='\033[1;31m'
RESET='\033[0m'

ccErr () {
	printf "\n${BOLD}${RED}ERPLAG compiler re-build failed.${RESET}\n"
}

input () {
	while :
	do
		read ans
		if test "$ans" = "y" -o "$ans" = "Y"
		then
			return
		elif  [ "$ans" = "n" -o "$ans" = "N" ]
		then
			exit 0
		else
			printf "\n${BOLD}${MAGENTA}Please re-enter correct option ${RESET}(y/n) "
		fi
	done
}

if ! [ -f /usr/local/bin/erplag ]
then
	printf "${BOLD}${MAGENTA}ERPLAG compiler is not installed!${RESET}\n" 
	printf "Please install the compiler with ${BOLD}${CYAN}./install ${RESET}before using ${BOLD}${CYAN}./rebuild${RESET}\n"

	exit 1
fi

printf "${BOLD}${CYAN}Proceed with re-building ERPLAG compiler? ${RESET}(y/n) "
input

sudo printf "Rebuilding ERPLAG compiler...\n\n"

make
if [ $? -ne 0 ]
then
	printf "\n${BOLD}${RED}ERPLAG compiler re-build failed! Please check the errors above\n${RESET}"
	exit 1
fi

sudo cp erplag /usr/local/bin
sudo cp .compiler /usr/local/bin
sudo cp erpclr /usr/local/bin

make clean

printf "\n${BOLD}${GREEN}ERPLAG compiler re-build OK!${RESET}\n"
